# Site settings
author: Dylan Teasdale
title: 
header-img: img/home-bg.png
email: dylan.teasdale@btinternet.com
copyright_name: Dylan Teasdale
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  dylanteasdale12

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
